import test from 'node:test';import assert from 'node:assert/strict';import {DatabaseSync} from 'node:sqlite';import {commentsAPI} from '../src/comments-api.mjs';
function db(){const sqlite=new DatabaseSync(':memory:');return {prepare(sql){return {args:[],bind(...args){this.args=args;return this},async run(){const result=sqlite.prepare(sql).run(...this.args);return {meta:{changes:result.changes}}},async all(){return {results:sqlite.prepare(sql).all(...this.args)}}}}}}
const origin='https://review.example';
const request=(method,body,extra={})=>new Request(origin+'/api/comments',{method,headers:{Origin:origin,'Content-Type':'application/json','oai-authenticated-user-email':'fabricated-reviewer@example.com',...extra},body:body?JSON.stringify(body):undefined});
test('shared comments persist and support addressed/reopen with bound text',async()=>{const env={DB:db()};const text="<script>alert('test')</script> ' ; DROP TABLE review_comments;";const saved=await commentsAPI(request('POST',{product:'duo',section:'compare',name:'QA reviewer',text}),env);assert.equal(saved.status,201);const c=(await saved.json()).comment;let list=await (await commentsAPI(request('GET'),env)).json();assert.equal(list.comments[0].text,text);assert.equal((await commentsAPI(request('PATCH',{id:c.id,status:'addressed'}),env)).status,200);list=await (await commentsAPI(request('GET'),env)).json();assert.equal(list.comments[0].status,'addressed');assert.equal((await commentsAPI(request('PATCH',{id:c.id,status:'open'}),env)).status,200)});
test('missing identity and foreign-origin writes are rejected',async()=>{assert.equal((await commentsAPI(new Request(origin+'/api/comments'),{DB:db()})).status,401);assert.equal((await commentsAPI(request('POST',{}, {Origin:'https://elsewhere.example'}),{DB:db()})).status,403)});
test('invalid context, oversized text and nonexistent updates fail clearly',async()=>{const env={DB:db()};for(const body of [{product:'bad',section:'compare',name:'QA',text:'x'},{product:'duo',section:'compare',name:'QA',text:'x'.repeat(2001)}])assert.equal((await commentsAPI(request('POST',body),env)).status,400);assert.equal((await commentsAPI(request('PATCH',{id:crypto.randomUUID(),status:'addressed'}),env)).status,404)});
test('whole-site contexts persist with page-specific section references',async()=>{const env={DB:db()};for(const [product,section] of [['home','opening'],['shop','catalogue'],['article-0','article'],['policy-shipping','policies'],['3-4-time','source-details']]){const r=await commentsAPI(request('POST',{product,section,name:'Fabricated QA',text:'Section review'}),env);assert.equal(r.status,201)}const result=await (await commentsAPI(request('GET'),env)).json();assert.equal(result.comments.length,5);assert.equal((await commentsAPI(request('POST',{product:'unknown-page',section:'opening',name:'QA',text:'x'}),env)).status,400)});
test('pins persist alongside existing comments, including new creator section',async()=>{const env={DB:db()};const pin={selector:'div:nth-of-type(1) > img:nth-of-type(1)',x:.2,y:.8};const r=await commentsAPI(request('POST',{product:'bergamot',section:'creator-stories',name:'QA',text:'Pinned note',pin}),env);assert.equal(r.status,201);const list=await (await commentsAPI(request('GET'),env)).json();assert.deepEqual(list.comments[0].pin,pin);assert.equal(list.comments[0].text,'Pinned note');for(const bad of [{...pin,x:2},{...pin,y:-1},{...pin,x:'0.5'},{...pin,selector:'x'.repeat(501)}])assert.equal((await commentsAPI(request('POST',{product:'home',section:'opening',name:'QA',text:'x',pin:bad}),env)).status,400)});
